
export const ADD_ACCOUNT = "add_account"
export const EDIT_SCORE = "edit_score"
export const INIT_LIST = "init_list"
export const ADD_ROW = "add_row"
export const DELETE_ROW = "delete_row"
export const CLEAR_DATA = "clean_dataSource"
export const CLEAR_COLUMN = "clean_column"
export const EDIT_MONEY = "edit_money"
export const UPDATE_TOTAL = "update_total"
export const SWITCH_ALL = "switch_double_for_all"
export const SWITCH_BOMB = "switch_double_for_bomb"
export const CHECK_DATA = "check_data"